Fixes for printing out files. Also fixed issue with CMakeLists.txt. In the cmake file, the source files were not listed.

diff --git a/geos b/geos
--- a/geos
+++ b/geos
@@ -52,7 +52,7 @@ load_variables() {
 # Go to the source directory before getting all the files.
 glob_files() {
     if [[ ! -d $source_directory ]]; then
-        >&2 echo "The source directory cannot be found! Please create a folder named \"src/\" and put your C/C++ files in it."
+        >&2 echo "The source directory cannot be found! Please create a folder named \"src\" and put your C/C++ files in it."
         exit 1
     fi
 
@@ -123,26 +123,12 @@ build() {
     rm -r $meta_directory 2> /dev/null
     cp -r src $meta_directory
 
-    C_MAKE_LISTS_FILE='file(GLOB ABI_FILES "*.abi")
-configure_file("${ABI_FILES}" "${CMAKE_CURRENT_BINARY_DIR}" COPYONLY)
+    C_MAKE_LISTS_FILE='file(GLOB ABI_FILES "*.abi")\nconfigure_file("${ABI_FILES}" "${CMAKE_CURRENT_BINARY_DIR}" COPYONLY)\n\nadd_wast_executable(TARGET '$contract_name'\n  INCLUDE_FOLDERS "${STANDARD_INCLUDE_FOLDERS}"\n  LIBRARIES libc++ libc eosiolib\n  DESTINATION_FOLDER ${CMAKE_CURRENT_BINARY_DIR}\n)'
 
-add_wast_executable(TARGET '$contract_name'
-  INCLUDE_FOLDERS "${STANDARD_INCLUDE_FOLDERS}"
-  LIBRARIES libc++ libc eosiolib
-  DESTINATION_FOLDER ${CMAKE_CURRENT_BINARY_DIR}
-)'
+    IDE_C_MAKE_LISTS_FILE='cmake_minimum_required(VERSION 3.9)\n\nproject('$contract_name')\n\nset(CMAKE_CXX_STANDARD 14)\n\ninclude_directories('$eosio_header_directory')\n\nadd_executable(messaging '$source_files')' > CMakeLists.txt
 
-    IDE_C_MAKE_LISTS_FILE='cmake_minimum_required(VERSION 3.9)
-project('$contract_name')
-
-set(CMAKE_CXX_STANDARD 14)
-
-include_directories('$eosio_header_directory')
-
-add_executable(messaging '$sourcefiles')' > CMakeLists.txt
-
-    echo $C_MAKE_LISTS_FILE > $meta_directory/CMakeLists.txt
-	echo $IDE_C_MAKE_LISTS_FILE > CMakeLists.txt
+    echo -e $C_MAKE_LISTS_FILE > $meta_directory/CMakeLists.txt
+	echo -e $IDE_C_MAKE_LISTS_FILE > CMakeLists.txt
 }
 
 usage() {
@@ -190,7 +176,7 @@ contract_name="'$contract_name'"
 eosio_header_directory="/usr/local/include/"
 
 base_directory=`dirname "$0"`
-source_directory="src/"
+source_directory="src"
 version='$VERSION > $contract_name/.geos
 
     cp $script_directory/$script_name $contract_name/$script_name
